# Site settings
name: Deyanira Taupier
title: Deyanira Taupier | Software Engineer
description: Back-end engineering, data, design, coding, programming, and fun.
keywords: Software Engineer, Software Developer, Software Development Engineer, Software Design Engineer, Programmer, Coder, Development, Design, Backend, Back-end, Back end, Full-Stack, Full Stack, Java, Python, Javascript, Go, Data Pipelines, Cloud, Data Science, Machine Learning, Deep Learning, Agile, Waterfall, Program, Deya, Deyanira, Taupier, Deyanira Taupier, miscdats, misc.dats, misc_dats, misc-dats
skills: Software Engineer in Seattle, WA

url: https://www.taupier.dev
baseurl: ''
email: deyanira@taupier.dev
cover: https://www.taupier.dev/images/spears.png
logo: https://www.taupier.dev/images/cyberpokeball.ico
resume: https://www.taupier.dev/DeyaniraTaupierResume.pdf

# Social networks usernames (ex. google-plus, flickr, dribbble, pinterest, instagram, tumblr, etc.)
social:
  - title: email
    url: mailto:deyanira@taupier.dev
  - title: github
    url: https://github.com/miscdats
  - title: linkedin
    url: https://www.linkedin.com/in/taupier
  # - title: repl.it
  #   url: https://repl.it/@miscdats
  # - title: twitter
  #   url: https://twitter.com/miscdats
  # - title: instagram
  #   url: https://instagram.com/miscdats
  # - title: codepen
  #   url: http://codepen.io/miscdats
  # - title: medium
  #   url: https://medium.com/@miscdats

# Google webmaster tools google site verification
google_verify: google-site-verification=ewbD4BNXy6cwwiWubHy-vfTLUgsh15uwEA9_TJ3P358

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 087e8b
  primary-rgb: "8, 126, 139"
  secondary: c1839f
  secondary-dark: ff5a5f
  section-tout: f5f5f5
  black: 3c3c3c

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap